name: realtime_location_tracking
description: Realtime background location tracking with Supabase
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State & Navigation
  provider: ^6.1.5+1
  go_router: ^17.0.0

  # Supabase
  supabase_flutter: ^2.12.0

  # Location
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # Background Service
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0

  # Web pages (About / Privacy)
  webview_flutter: ^4.13.0

  # Utilities
  uuid: ^4.5.2
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  awesome_dialog: ^3.3.0
  image_picker: ^0.8.7+5
  crypto: ^3.0.7
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_local_notifications: ^19.5.0
  android_alarm_manager_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
